# $schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
# name: blue
# endpoint_name: fragrance-sentiment-endpoint

# model: azureml:fragrance-sentiment-logreg@latest

# environment:
#   image: mcr.microsoft.com/azureml/minimal-ubuntu20.04-py38-cpu-inference
#   conda_file: ../azureml/conda.yml

# code_configuration:
#   code: src/inference
#   scoring_script: score.py

# instance_type: Standard_DS2_v2
# instance_count: 1

# environment_variables:
#   INFERENCE_LOG_CONTAINER: inference-logs

$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: fragrance-sentiment-endpoint

model: azureml:fragrance-sentiment-logreg:10


environment:
  image: mcr.microsoft.com/azureml/minimal-ubuntu20.04-py38-cpu-inference:20240603.v1
  conda_file: azureml/conda-infer.yml

code_configuration:
  code: ../src/inference
  scoring_script: score.py

instance_type: Standard_DS2_v2
instance_count: 1

environment_variables:
  INFERENCE_LOG_CONTAINER: inference-logs
  AZURE_STORAGE_CONNECTION_STRING: ""



